fix(utils): bone offset
darktrovx/interact pull request #21
Opened 2024-03-02 00:51 UTC by snalye

Makes offsets with bones functional

2024-03-02 03:16 UTC, snalye commented
Added options per job

## With Job
![img](https://i.imgur.com/hg9vTps.png)

## Without Job
![img](https://i.imgur.com/rpLi1ni.png)

2024-03-03 02:02 UTC, FjamZoo requested changes

2024-03-03 02:02 UTC, FjamZoo commented on client/interactions.lua
> +                end
```suggestion
                if not option.job or hasGroup(option.job) then
                        added += 1
                        currentOptions[added] = option
                end
```

2024-03-03 02:03 UTC, FjamZoo commented on client/interactions.lua
> +                end
No reason to make a if-else statement jsut follow what I've done previously and use if not option.job or hasGroup(option.job)

2024-03-03 05:11 UTC, merged